name: CI
run-name: ${{ github.actor }} CV
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
      - name: Build
        run: npm install
      - name: Generate CV Pdf
        run: npm run pdf
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf